### PR TITLE
Auto-merge Go PRs for patch dependency upgrades

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/giantswarm/issues/28741

This should reduce human intervention in the cases where dependencies are updated with non-breaking changes.

For the affected Go projects this means: Renovate will merge dependency update PRs automatically once all checks are green.

Please watch your repositories and check whether these safeguards are in place:

- Compilation(at least `go test`) happens during a CI/CD check
- and is required per branch protection rule for the default branch

### CODE REVIEW

**Review by AverageMarcus — COMMENTED** [review]
👍  from me but I'd like to get more input from other teams first before merging this in.

**Review by fiunchinho — APPROVED** [review]

**Comment by marians** [comment]
To reduce the blast radius, I changed the config to only allow automerge for patch upgrades. Once we gathered some experience with that, we can extend this to minor etc.

**Review by mcharriere — APPROVED** [review]
looking forward for this :)

**Comment by marians** [comment]
OK, let's go. This has been open long enough.

**Pull request merged**
